#                  List of Armour
#                 ~~~~~~~~~~~~~~~~~

#------------------------------------------------------
#     Full Outfits (If selected others don't apply)
#------------------------------------------------------

#               Bomb Squad (Full Outfit)
#         (decrease explosion damage by 3x)
#         (decrease melee damage by 1.5x)
#         (decrease movement speed by 1.2x)
#         (increase defuse time by 2x)
#         (decrease reload speed by 1.5x)



#------------------------------------------------------

#             Stealth Suit (Full Outfit)
#        (decrease chance of being hit by 2x)
#        (increases run speed by 1.2x)
#        (increases melee damage by 1.5x)



#------------------------------------------------------
#                    Helmets
#------------------------------------------------------

#                    Default



#------------------------------------------------------

#                    Gas Mask
#             (Immune to toxic gases)



#------------------------------------------------------

#               Night Vision Goggles
#            (Able to see in the dark)



#------------------------------------------------------
#                   Chest | Gloves
#------------------------------------------------------

#                      Default



#------------------------------------------------------

#                      Deadeye
#   (increase precision & chances of hitting by 2x)



#------------------------------------------------------

#                     Gunslinger
#            (decreases reload time by 2x)



#------------------------------------------------------

#                      Assassin
#            (increases melee damage by 1.75x)



#------------------------------------------------------
#                       Pants
#------------------------------------------------------

#                      Default



#------------------------------------------------------

#                      Waiders (boot combo)
#     (increase movement speed in water by 1.5x)



#------------------------------------------------------

#                 Extra Holsters Rank 1
#                 (Holds 1 extra mag)



#------------------------------------------------------

#                 Extra Holsters Rank 2
#            (Holds 1 extra item(grenade,etc)



#------------------------------------------------------

#                 Extra Holsters Rank 3
#                 (Holds 2 extra mags)



#------------------------------------------------------

#                 Extra Holsters Rank 4
#           (Holds 1 extra mag and 1 extra item)




#------------------------------------------------------
#                       Boots
#------------------------------------------------------

#                      Default



#------------------------------------------------------

#                  Runners Delight
#             (Increase run speed by 1.2x)



#------------------------------------------------------

#               Rock Climbing Boots
#       (Increase jump by 1.5x when near a cliff)



#------------------------------------------------------

#              Slip Resistant Boots
#     (Removes slipping on ice, or in swamps)



#------------------------------------------------------

#                 Ninja Slippers     
#        (removes noise when walking/running)



#------------------------------------------------------
