#toybox for 2.0 - rendition by Elite
#box = Toybox inside the toybox
#n = not unlocked (requires certain supporter level or bought with tickets or bought in store)
#b = bought shop item
#u = not purchased shop item
#e = 1 (enabled) in use - or activated
#d = 0 (disabled) not in use - or deactivated
#g = given item - the item the player is able to use outside of the chest gui.

options:
	gHelp: book named "&6&lOBAM&fCraft &3Guide" with lore "&7Right click this book||&7to &6learn&7 all about OBAM."
	gWorlds: ender pearl named "&3Game &dWorlds" with lore "&7Right click this item to &dview&7||&7the available Game Worlds!"
	gFly: feather named "&6&l≾&3Fly&6&l≿" with lore "&7Right click this||&7to &3fly &7in hub!"
	#
	dSkyblock: i;grass;n;&6Skyblock;l;&7Try our Skyblock world||&7with &dCustom Challenges||&7and &9Villager Trading&7!;c;sudo %player% worlds skyblock
	dFronts: i;cobblestone;n;&6Fronts;l;&7Our Special flavour of||&7Survival with &binstant&7||&7land claiming!;c;sudo %player% worlds survival
	dWtfronts: i;magma cream;n;&6WTFronts;l;&cBETA TESTING|| ||&7Extreme Survival||&7with &cextreme&7 payoffs!;c;sudo %player% worlds wtf
	dKitpvp: i;blaze rod;n;&6Kit PVP;l;&7Play OBAM's KitPvP||&7with &anew&7 original kits!;c;sudo %player% worlds kit
	dGarage: i;tripwire hook;n;&6Garage;l;&7The Testing Server|| ||&7Where things get fixed.;c;sudo %player% worlds garage
	#
	gToybox: ender chest named "&2Toy &9Box" with lore "&7Click to &2open&7 the toy box.||&7See what toys you may use."
	#
	gEffectmachine: ender portal frame named "&3The &2Effect &3Machine" with lore "&7Click to &3activate&7||&7the effect machine."
	#
	uEffect: i;nether star;n;&6Unstable &fGases;l;&3Not Purchased|| ||&aPrice: 5,000 tickets||&5Click to Buy.;c;sudo %player% effect magic
	bEffect: i;nether star;n;&6Unstable &fGases;l;&aBought|| ||&eYou already have this unlocked.;c;sudo %player% effect magic
	nEffect: i;nether star;n;&6Unstable &fGases;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect shop
	eEffect: i;nether star;n;&6Unstable &fGases;l;&aEnabled|| ||&fClick to &cDisable;c;sudo %player% effectmachine magic
	dEffect: i;nether star;n;&6Unstable &fGases;l;&cDisabled|| ||&fClick to &aEnable;c;sudo %player% effectmachine magic
	#
	dDisguise: i;iron door item;n;&6Disguise &fCloset;l;&fClick to &9Open &fyour closet;c;sudo %player% effectmachine disguise
	#
	eBoat: i;boat;n;&6Boat;l;&aEnabled|| ||&fClick to &cDisable;c;sudo %player% toybox boat
	dBoat: i;boat;n;&6Boat;l;&cDisabled|| ||&fClick to &aEnable;c;sudo %player% toybox boat
	gBoat: boat named "&3%player%'s &fBoat" with lore "&3Travel&7 the majestic waters||&7of the hub with this boat!"
	#
	eCart: i;storage minecart;n;&6MineCart;l;&aEnabled|| ||&fClick to &cDisable;c;sudo %player% toybox cart
	dCart: i;powered minecart;n;&6MineCart;l;&cDisabled|| ||&fClick to &aEnable;c;sudo %player% toybox cart
	gCart: minecart named "&3%player%'s &fCart" with lore "&7Want to sore on the track?||&3Place&7 this cart down . . .|| ||&5Let's take it for a spin."
	#
	uFirework: i;firework rocket;n;&6OBAM&fCraft &6Firework;l;&3Not Purchased|| ||&aPrice: 2,500 tickets||&5Click to Buy.;c;sudo %player% toy firework
	bFirework: i;firework rocket;n;&6OBAM&fCraft &6Firework;l;&aBought|| ||&eYou already have this unlocked.;c;sudo %player% toy firework
	nFirework: i;firework rocket;n;&6OBAM&fCraft &6Firework;l;&3Not Unlocked|| ||&eType &f/toy shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% toy shop
	eFirework: i;firework rocket;n;&6OBAM&fCraft &6Firework;l;&aEnabled|| ||&fClick to &cDisable;c;sudo %player% toybox firework
	dFirework: i;firework rocket;n;&6OBAM&fCraft &6Firework;l;&cDisabled|| ||&fClick to &aEnable;c;sudo %player% toybox firework
	gFirework: firework rocket named "&6OBAM&fCraft &3Firework" with lore "&7Right click to &3see&7 a random||&7OBAM themed firework effect.|| ||&73 Second Cooldown"
	#
	uPiston: i;piston base;n;&6Player&fPusher;l;&3Not Purchased|| ||&aPrice: 5,000 tickets||&5Click to Buy.;c;sudo %player% toy piston
	bPiston: i;piston base;n;&6Player&fPusher;l;&aBought|| ||&eYou already have this unlocked.;c;sudo %player% toy piston
	nPiston: i;piston base;n;&6Player&fPusher;l;&3Not Unlocked|| ||&eType &f/toy shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% toy shop
	ePiston: i;piston base;n;&6Player&fPusher;l;&aEnabled|| ||&fClick to &cDisable;c;sudo %player% toybox piston
	dPiston: i;piston base;n;&6Player&FPusher;l;&cDisabled|| ||&fClick to &aEnable;c;sudo %player% toybox piston
	gPiston: piston base named "&3Player&fPusher" with lore "&7Use this to &3push&7 players around.|| ||&5How to use: Punch someone while holding it."
	#
	tShop: i;nether quartz ore;n;&2Toy &9Shop;l;&7Click to &2travel&7 to||&7the toy shop;c;sudo %player% toy shop
	eShop: i;bottle of enchanting;n;&2Effect &9Shop;l;&7Click to &2travel&7 to||&7the effect shop;c;sudo %player% effect shop
	dShop: i;head item;n;&2Disguise &9Shop;l;&7Click to &2look&7 inside||&7the disguise shop;c;sudo %player% effect disguise
	#
	dStop: s;54;i;red wool;n; ;l;&fClick here to||&c Undisguise;c;sudo %player% disguiseset remove
	#
	#replace dStop item with barrier after 1.8
	#
	eDspecial: s;45;i;dragon egg;n;&9Specials
	dDspecial: s;45;i;dragon egg;n;&9Specials
	
on join:
	#execute console command "/mv tp %player% Death-Hub"
	#clear player's inventory
	#player is in "death-hub"
	if {db_effectshop.effect.%player%} is not set:
		set {db_effectshop.effect.%player%} to false
	if {db_effectshop.disguise.%player%} is not set:
		set {db_effectshop.disguise.%player%} to false
	if {db_toyshop.firework.%player%} is not set:
		set {db_toyshop.firework.%player%} to false
	if {db_toyshop.piston.%player%} is not set:
		set {db_toyshop.piston.%player%} to false
	if {db_effectshop.disguises.creeper.%player%} is not set:
		set {db_effectshop.disguises.creeper.%player%} to false
	if {db_effectshop.disguises.skeleton.%player%} is not set:
		set {db_effectshop.disguises.skeleton.%player%} to false
	if {db_effectshop.disguises.spider.%player%} is not set:
		set {db_effectshop.disguises.spider.%player%} to false
	if {db_effectshop.disguises.zombie.%player%} is not set:
		set {db_effectshop.disguises.zombie.%player%} to false
	if {db_effectshop.disguises.slime.%player%} is not set:
		set {db_effectshop.disguises.slime.%player%} to false
	if {db_effectshop.disguises.ghast.%player%} is not set:
		set {db_effectshop.disguises.ghast.%player%} to false
	if {db_effectshop.disguises.zombiepigman.%player%} is not set:
		set {db_effectshop.disguises.zombiepigman.%player%} to false
	if {db_effectshop.disguises.enderman.%player%} is not set:
		set {db_effectshop.disguises.enderman.%player%} to false
	if {db_effectshop.disguises.cavespider.%player%} is not set:
		set {db_effectshop.disguises.cavespider.%player%} to false
	if {db_effectshop.disguises.silverfish.%player%} is not set:
		set {db_effectshop.disguises.silverfish.%player%} to false
	if {db_effectshop.disguises.blaze.%player%} is not set:
		set {db_effectshop.disguises.blaze.%player%} to false
	if {db_effectshop.disguises.magmacube.%player%} is not set:
		set {db_effectshop.disguises.magmacube.%player%} to false
	if {db_effectshop.disguises.bat.%player%} is not set:
		set {db_effectshop.disguises.bat.%player%} to false
	if {db_effectshop.disguises.witch.%player%} is not set:
		set {db_effectshop.disguises.witch.%player%} to false
	if {db_effectshop.disguises.pig.%player%} is not set:
		set {db_effectshop.disguises.pig.%player%} to false
	if {db_effectshop.disguises.sheep.%player%} is not set:
		set {db_effectshop.disguises.sheep.%player%} to false
	if {db_effectshop.disguises.cow.%player%} is not set:
		set {db_effectshop.disguises.cow.%player%} to false
	if {db_effectshop.disguises.chicken.%player%} is not set:
		set {db_effectshop.disguises.chicken.%player%} to false
	if {db_effectshop.disguises.squid.%player%} is not set:
		set {db_effectshop.disguises.squid.%player%} to false
	if {db_effectshop.disguises.wolf.%player%} is not set:
		set {db_effectshop.disguises.wolf.%player%} to false
	if {db_effectshop.disguises.mooshroom.%player%} is not set:
		set {db_effectshop.disguises.mooshroom.%player%} to false
	if {db_effectshop.disguises.ocelot.%player%} is not set:
		set {db_effectshop.disguises.ocelot.%player%} to false
	if {db_effectshop.disguises.horse.%player%} is not set:
		set {db_effectshop.disguises.horse.%player%} to false
	if {db_effectshop.disguises.villager.%player%} is not set:
		set {db_effectshop.disguises.villager.%player%} to false
	#
	player is in "world":
		player does not have a {@gHelp}:
			give 1 {@gHelp} to player
		player does not have a {@gWorlds}:
			give 1 {@gWorlds} to player
		player does not have a {@gFly}:
			give 1 {@gFly} to player			
		give 1 stone to player
		give 1 grass block to player
		give 1 dirt to player
		player does not have a {@gToybox}:
			give 1 {@gToybox} to player
		give 1 cobblestone to player
		player does not have a {@gEffectmachine}:
			give 1 {@gEffectmachine} to player	
		#
		if {boatstop.%player%} is not set:
			set {boatstop.%player%} to false
		if {boatstop.%player%} is true:
			set {boatstop.%player%} to false
		if {cartstop.%player%} is not set:
			set {cartstop.%player%} to false
		if {cartstop.%player%} is true:
			set {cartstop.%player%} to false
		if {toybox.boat.%player%} is not set:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is not set:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is not set:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is not set:
			set {toybox.piston.%player%} to 0
		#
		if {effects.magic.%player%} is not set:
			set {effects.magic.%player%} to 0
		#
		if {toybox.boat.%player%} is 1:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is 1:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is 1:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is 1:
			set {toybox.piston.%player%} to 0
		#	
		if {effects.disguises.creeper.%player%} is 1:
			set {effects.disguises.creeper.%player%} to 0
		if {effects.disguises.skeleton.%player%} is 1:
			set {effects.disguises.skeleton.%player%} to 0		
		if {effects.disguises.spider.%player%} is 1:
			set {effects.disguises.spider.%player%} to 0
		if {effects.disguises.zombie.%player%} is 1:
			set {effects.disguises.zombie.%player%} to 0
		if {effects.disguises.slime.%player%} is 1:
			set {effects.disguises.slime.%player%} to 0
		if {effects.disguises.ghast.%player%} is 1:
			set {effects.disguises.ghast.%player%} to 0		
		if {effects.disguises.zombiepigman.%player%} is 1:
			set {effects.disguises.zombiepigman.%player%} to 0
		if {effects.disguises.enderman.%player%} is 1:
			set {effects.disguises.enderman.%player%} to 0
		if {effects.disguises.cavespider.%player%} is 1:
			set {effects.disguises.cavespider.%player%} to 0
		if {effects.disguises.silverfish.%player%} is 1:
			set {effects.disguises.silverfish.%player%} to 0		
		if {effects.disguises.blaze.%player%} is 1:
			set {effects.disguises.blaze.%player%} to 0
		if {effects.disguises.magmacube.%player%} is 1:
			set {effects.disguises.magmacube.%player%} to 0
		if {effects.disguises.bat.%player%} is 1:
			set {effects.disguises.bat.%player%} to 0
		if {effects.disguises.witch.%player%} is 1:
			set {effects.disguises.witch.%player%} to 0		
		if {effects.disguises.pig.%player%} is 1:
			set {effects.disguises.pig.%player%} to 0
		if {effects.disguises.sheep.%player%} is 1:
			set {effects.disguises.sheep.%player%} to 0
		if {effects.disguises.cow.%player%} is 1:
			set {effects.disguises.cow.%player%} to 0
		if {effects.disguises.chicken.%player%} is 1:
			set {effects.disguises.chicken.%player%} to 0		
		if {effects.disguises.squid.%player%} is 1:
			set {effects.disguises.squid.%player%} to 0
		if {effects.disguises.wolf.%player%} is 1:
			set {effects.disguises.wolf.%player%} to 0
		if {effects.disguises.mooshroom.%player%} is 1:
			set {effects.disguises.mooshroom.%player%} to 0
		if {effects.disguises.ocelot.%player%} is 1:
			set {effects.disguises.ocelot.%player%} to 0		
		if {effects.disguises.horse.%player%} is 1:
			set {effects.disguises.horse.%player%} to 0
		if {effects.disguises.villager.%player%} is 1:
			set {effects.disguises.villager.%player%} to 0
		#
		if {effects.magic.%player%} is 1:
			set {effects.magic.%player%} to 0
		set {disguise.type.%player%} to "creeper"
		#
		clear {time.set.%player%}
		#
		{fly.hub.%player%} is true:
			set fly state of player to true
		#
		remove all stone from player's inventory
		remove all grass block from player's inventory
		remove all dirt from player's inventory
		remove all cobblestone from player's inventory
		
on inventory click:
	player is in "world":
		cancel event
		
on respawn:
	#player is in "death-hub"
	if {db_effectshop.effect.%player%} is not set:
		set {db_effectshop.effect.%player%} to false
	if {db_toyshop.firework.%player%} is not set:
		set {db_toyshop.firework.%player%} to false
	if {db_toyshop.piston.%player%} is not set:
		set {db_toyshop.piston.%player%} to false
	#
	player is in "world":
		player does not have a {@gHelp}:
			give 1 {@gHelp} to player
		player does not have a {@gWorlds}:
			give 1 {@gWorlds} to player
		player does not have a {@gFly}:
			give 1 {@gFly} to player			
		give 1 stone to player
		give 1 grass block to player
		give 1 dirt to player
		player does not have a {@gToybox}:
			give 1 {@gToybox} to player
		give 1 cobblestone to player
		player does not have a {@gEffectmachine}:
			give 1 {@gEffectmachine} to player	
		#
		if {boatstop.%player%} is not set:
			set {boatstop.%player%} to false
		if {boatstop.%player%} is true:
			set {boatstop.%player%} to false
		if {cartstop.%player%} is not set:
			set {cartstop.%player%} to false
		if {cartstop.%player%} is true:
			set {cartstop.%player%} to false
		if {toybox.boat.%player%} is not set:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is not set:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is not set:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is not set:
			set {toybox.piston.%player%} to 0
		#
		if {toybox.boat.%player%} is 1:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is 1:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is 1:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is 1:
			set {toybox.piston.%player%} to 0
		#
		if {effects.magic.%player%} is 1:
			set {effects.magic.%player%} to 0
		#
		clear {time.set.%player%}
		#
		{fly.hub.%player%} is true:
			set fly state of player to true
		#
		remove all stone from player's inventory
		remove all grass block from player's inventory
		remove all dirt from player's inventory
		remove all cobblestone from player's inventory
			
command /sudo <player> <text>:
	executable by: console
	trigger:
		make argument 1 execute command "%argument 2%"
		
command /purge <text>:
	executable by: players
	permission: obam.admin
	trigger:
		if argument is "boat":
			loop all entities in player's world:
				if loop-entity is a boat:
					delete loop-entity
			if player is in "world":
				loop all players in player's world:
					set {boatstop.%loop-player%} to false
					set {toybox.boat.%loop-player%} to 0
					remove all {@gBoat} from loop-player's inventory
			broadcast "&fPurging all boats!" to the player's world
			stop
		if argument is "cart" or "minecart":
			loop all entities in player's world:
				if loop-entity is a minecart:
					delete loop-entity
			if player is in "world":
				loop all players in player's world:
					set {cartstop.%loop-player%} to false
					set {toybox.cart.%loop-player%} to 0
					remove all {@gCart} from loop-player's inventory
			broadcast "&fPurging all carts!" to the player's world
			stop
		send "&fPlease Use The Correct Usage:" to player
		send "&e/purge cart" to player
		send "&e/purge boat" to player
		stop

on teleport:
	#player is in "death-hub"
	wait 1 second
	player's world is "world":
		{fly.hub.%player%} is true:
			set fly state of player to true
		player does not have a {@gHelp}:
			give 1 {@gHelp} to player
		player does not have a {@gWorlds}:
			give 1 {@gWorlds} to player
		player does not have a {@gFly}:
			give 1 {@gFly} to player			
		give 1 stone to player
		give 1 grass block to player
		give 1 dirt to player
		player does not have a {@gToybox}:
			give 1 {@gToybox} to player
		give 1 cobblestone to player
		player does not have a {@gEffectmachine}:
			give 1 {@gEffectmachine} to player
		#
		if {boatstop.%player%} is not set:
			set {boatstop.%player%} to false
		if {boatstop.%player%} is true:
			set {boatstop.%player%} to false
		if {cartstop.%player%} is not set:
			set {cartstop.%player%} to false
		if {cartstop.%player%} is true:
			set {cartstop.%player%} to false
		if {toybox.boat.%player%} is not set:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is not set:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is not set:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is not set:
			set {toybox.piston.%player%} to 0
		#	
		if {effects.disguises.creeper.%player%} is 1:
			set {effects.disguises.creeper.%player%} to 0
		if {effects.disguises.skeleton.%player%} is 1:
			set {effects.disguises.skeleton.%player%} to 0		
		if {effects.disguises.spider.%player%} is 1:
			set {effects.disguises.spider.%player%} to 0
		if {effects.disguises.zombie.%player%} is 1:
			set {effects.disguises.zombie.%player%} to 0
		if {effects.disguises.slime.%player%} is 1:
			set {effects.disguises.slime.%player%} to 0
		if {effects.disguises.ghast.%player%} is 1:
			set {effects.disguises.ghast.%player%} to 0		
		if {effects.disguises.zombiepigman.%player%} is 1:
			set {effects.disguises.zombiepigman.%player%} to 0
		if {effects.disguises.enderman.%player%} is 1:
			set {effects.disguises.enderman.%player%} to 0
		if {effects.disguises.cavespider.%player%} is 1:
			set {effects.disguises.cavespider.%player%} to 0
		if {effects.disguises.silverfish.%player%} is 1:
			set {effects.disguises.silverfish.%player%} to 0		
		if {effects.disguises.blaze.%player%} is 1:
			set {effects.disguises.blaze.%player%} to 0
		if {effects.disguises.magmacube.%player%} is 1:
			set {effects.disguises.magmacube.%player%} to 0
		if {effects.disguises.bat.%player%} is 1:
			set {effects.disguises.bat.%player%} to 0
		if {effects.disguises.witch.%player%} is 1:
			set {effects.disguises.witch.%player%} to 0		
		if {effects.disguises.pig.%player%} is 1:
			set {effects.disguises.pig.%player%} to 0
		if {effects.disguises.sheep.%player%} is 1:
			set {effects.disguises.sheep.%player%} to 0
		if {effects.disguises.cow.%player%} is 1:
			set {effects.disguises.cow.%player%} to 0
		if {effects.disguises.chicken.%player%} is 1:
			set {effects.disguises.chicken.%player%} to 0		
		if {effects.disguises.squid.%player%} is 1:
			set {effects.disguises.squid.%player%} to 0
		if {effects.disguises.wolf.%player%} is 1:
			set {effects.disguises.wolf.%player%} to 0
		if {effects.disguises.mooshroom.%player%} is 1:
			set {effects.disguises.mooshroom.%player%} to 0
		if {effects.disguises.ocelot.%player%} is 1:
			set {effects.disguises.ocelot.%player%} to 0		
		if {effects.disguises.horse.%player%} is 1:
			set {effects.disguises.horse.%player%} to 0
		if {effects.disguises.villager.%player%} is 1:
			set {effects.disguises.villager.%player%} to 0
		if {effects.magic.%player%} is not set:
			set {effects.magic.%player%} to 0
		if {effects.disguise.%player%} is not set:
			set {effects.disguise.%player%} to 0
		#
		if {toybox.boat.%player%} is 1:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is 1:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is 1:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is 1:
			set {toybox.piston.%player%} to 0
		#
		if {effects.magic.%player%} is 1:
			set {effects.magic.%player%} to 0
		set {disguise.type.%player%} to "creeper"
		#
		remove all stone from player's inventory
		remove all grass block from player's inventory
		remove all dirt from player's inventory
		remove all cobblestone from player's inventory
	player's world is not "world":
		{fly.hub.%player%} is true:
			set fly state of player to false
		if {boatstop.%player%} is true:
			delete vehicle of player
			set {boatstop.%player%} to false
		if {cartstop.%player%} is true:
			delete vehicle of player
			set {cartstop.%player%} to false
		if {toybox.boat.%player%} is 1:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is 1:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is 1:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is 1:
			set {toybox.piston.%player%} to 0
		#
		if {effects.magic.%player%} is 1:
			set {effects.magic.%player%} to 0
		#
		if {disguise.set.%player%} is true:
			make console execute command "/undisguiseplayer %player%"
			set {disguise.set.%player%} to false
		#
		if player has {@gHelp}:
			remove all {@gHelp} from player's inventory
		if player has {@gWorlds}:
			remove all {@gWorlds} from player's inventory
		if player has {@gFly}:
			remove all {@gFly} from player's inventory
		if player has {@gToybox}:
			remove all {@gToybox} from player's inventory
		if player has {@gEffectmachine}:
			remove all {@gEffectmachine} from player's inventory
		if player has {@gBoat}:
			remove all {@gBoat} from player's inventory
		if player has {@gCart}:
			remove all {@gCart} from player's inventory
		if player has {@gFirework}:
			remove all {@gFirework} from player's inventory
		if player has {@gPiston}:
			remove all {@gPiston} from player's inventory
		clear {time.set.%player%}
		#
		loop all entities in player's world:
			if loop-entity is a boat:
				if name of loop-entity is "&3%player%'s &fBoat":
					delete loop-entity
			if loop-entity is a minecart:
				if name of loop-entity is "&3%player%'s &fCart":
					delete loop-entity
			
on place:
	player is in "world":
		player's tool is {@gToybox}:
			cancel event
			remove all {@gToybox} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gToybox} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
			stop
		player's tool is {@gEffectmachine}:
			cancel event
			remove all {@gEffectmachine} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			if {toybox.boat.%player%} is 0:
				if {toybox.cart.%player%} is 0:
					if {toybox.firework.%player%} is 0:
						if {toybox.piston.%player%} is 0:
							give 1 cobblestone to player				
			give 1 {@gEffectmachine} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
			remove all cobblestone from player's inventory		
		player's tool is {@gPiston}:
			cancel event
			remove all {@gPiston} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gPiston} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
			stop
		player's tool is {@gBoat}:
			if {boatstop.%player%} is false:
				set {boatstop.%player%} to true
				if player has {@gBoat}:
					remove all {@gBoat} from player's inventory
				stop
		player's tool is {@gCart}:
			if {cartstop.%player%} is false:
				set {cartstop.%player%} to true
				if player has {@gCart}:
					remove all {@gCart} from player's inventory
				stop
				
on click:
	player is in "world":
		player's tool is {@gToybox}:
			make player execute command "/toybox"
		player's tool is {@gEffectmachine}:
			make player execute command "/effectmachine"
			
on left click:
	player is in "world":
		player's tool is {@gPiston}:
			if distance between player and targeted entity is less than 6:
				if targeted entity is a player:
					push the targeted entity in the direction of the player at speed 1
			
on right click:
	player is in "world":
		player's tool is {@gHelp}:
			make player execute command "/help"
			stop
		player's tool is {@gWorlds}:
			cancel event
			make player execute command "/worlds"
			stop
		player's tool is {@gFly}:
			make player execute command "/flight"
			stop
		player's tool is {@gFirework}:
			cancel event
			if {time.set.%player%} is not set:
				if distance between player and targeted block is less than 6:
					set {time.set.%player%} to now
					set {_firework.loc.%player%} to location of targeted block
					shoot firework rocket from targeted block at speed 1 upward
					add 10 to y-coordinate of {_firework.loc.%player%}
					wait 1 second
					set {_ran.type.num.%player%} to a random number between 1 and 15
					wait 1 second
					if {_ran.type.num.%player%} is 1:
						pop ball colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 2:
						pop ball colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 3:
						pop ball colored gold at {_firework.loc.%player%}
						pop ball colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 4:
						pop ball large colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 5:
						pop ball large colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 6:
						pop ball large colored gold at {_firework.loc.%player%}
						pop ball large colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 7:
						pop burst colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 8:
						pop burst colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 9:
						pop burst colored gold at {_firework.loc.%player%}
						pop burst colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 10:
						pop creeper colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 11:
						pop creeper colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 12:
						pop creeper colored gold at {_firework.loc.%player%}
						pop creeper colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 13:
						pop star colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 14:
						pop star colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 15:
						pop star colored gold at {_firework.loc.%player%}
						pop star colored dark aqua at {_firework.loc.%player%}
						stop
			if {time.set.%player%} is set:
				if difference between {time.set.%player%} and now is smaller than 1 second:
					send "&eYou must wait 3 seconds before you may use this." to player
					stop
				if difference between {time.set.%player%} and now is smaller than 2 seconds:
					send "&eYou must wait 2 seconds before you may use this." to player
					stop
				if difference between {time.set.%player%} and now is smaller than 3 seconds:
					send "&eYou must wait 1 second before you may use this." to player
					stop
				if distance between player and targeted block is less than 6:
					set {time.set.%player%} to now
					set {_firework.loc.%player%} to location of targeted block
					shoot firework rocket from targeted block at speed 1 upward
					add 10 to y-coordinate of {_firework.loc.%player%}
					wait 1 second
					set {_ran.type.num.%player%} to a random number between 1 and 15
					wait 1 second
					if {_ran.type.num.%player%} is 1:
						pop ball colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 2:
						pop ball colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 3:
						pop ball colored gold at {_firework.loc.%player%}
						pop ball colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 4:
						pop ball large colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 5:
						pop ball large colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 6:
						pop ball large colored gold at {_firework.loc.%player%}
						pop ball large colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 7:
						pop burst colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 8:
						pop burst colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 9:
						pop burst colored gold at {_firework.loc.%player%}
						pop burst colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 10:
						pop creeper colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 11:
						pop creeper colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 12:
						pop creeper colored gold at {_firework.loc.%player%}
						pop creeper colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 13:
						pop star colored gold at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 14:
						pop star colored dark aqua at {_firework.loc.%player%}
						stop
					if {_ran.type.num.%player%} is 15:
						pop star colored gold at {_firework.loc.%player%}
						pop star colored dark aqua at {_firework.loc.%player%}
						stop
	
on vehicle enter:
	world is "world":
		if vehicle is a boat:
			if the name of the boat is not "&3%player%'s &fBoat":
				cancel event
				send "&fThis is not your boat." to player
				stop
		if vehicle is a minecart:
			if the name of the minecart is not "&3%player%'s &fCart":
				cancel event
				send "&fThis is not your cart." to player
				stop
				
on pick up:
	world is "world":
		cancel event
	
on vehicle exit:
	#player is in "death-hub"
	player is in "world":
		if {boatstop.%player%} is true:
			delete vehicle of player
			set {boatstop.%player%} to false
		if {cartstop.%player%} is true:
			delete vehicle of player
			set {cartstop.%player%} to false
			
on vehicle damage:
	world is "world":
		cancel event
		
on vehicle destroy:
	world is "world":
		cancel event
		
on disconnect:
	#player is in "death-hub"
	player is in "world":
		if {boatstop.%player%} is true:
			delete vehicle of player
			set {boatstop.%player%} to false
		if {cartstop.%player%} is true:
			delete vehicle of player
			set {cartstop.%player%} to false
		if {toybox.boat.%player%} is 1:
			set {toybox.boat.%player%} to 0
		if {toybox.cart.%player%} is 1:
			set {toybox.cart.%player%} to 0
		if {toybox.firework.%player%} is 1:
			set {toybox.firework.%player%} to 0
		if {toybox.piston.%player%} is 1:
			set {toybox.piston.%player%} to 0
		#
		if {effects.magic.%player%} is 1:
			set {effects.magic.%player%} to 0
		#
		if {disguise.set.%player%} is true:
			make console execute command "/undisguiseplayer %player%"
			set {disguise.set.%player%} to false
		#
		if player has {@gHelp}:
			remove all {@gHelp} from player's inventory
		if player has {@gWorlds}:
			remove all {@gWorlds} from player's inventory
		if player has {@gFly}:
			remove all {@gFly} from player's inventory
		if player has {@gToybox}:
			remove all {@gToybox} from player's inventory
		if player has {@gEffectmachine}:
			remove all {@gEffectmachine} from player's inventory
		if player has {@gBoat}:
			remove all {@gBoat} from player's inventory
		if player has {@gCart}:
			remove all {@gCart} from player's inventory
		if player has {@gFirework}:
			remove all {@gFirework} from player's inventory
		if player has {@gPiston}:
			remove all {@gPiston} from player's inventory
		clear {time.set.%player%}
		#
		loop all entities in player's world:
			if loop-entity is a boat:
				if name of loop-entity is "&3%player%'s &fBoat":
					delete loop-entity
			if loop-entity is a minecart:
				if name of loop-entity is "&3%player%'s &fCart":
					delete loop-entity
	
on shoot:
	world is "world":
		shooter's tool is ender pearl:
			cancel event
				
on damage:
	world is "world":
		cancel event
	
on drop:
	player is in "world":
		event-item is {@gHelp}:
			cancel event
		event-item is {@gWorlds}:
			cancel event
		event-item is {@gFly}:
			cancel event
		event-item is {@gToybox}:
			cancel event
			remove all {@gToybox} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gToybox} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
		event-item is {@gEffectmachine}:
			cancel event
			remove all {@gEffectmachine} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			if {toybox.boat.%player%} is 0:
				if {toybox.cart.%player%} is 0:
					if {toybox.firework.%player%} is 0:
						if {toybox.piston.%player%} is 0:
							if {boatstop.%player%} is false:
								if {cartstop.%player%} is false:
									give 1 cobblestone to player				
			give 1 {@gEffectmachine} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
			remove all cobblestone from player's inventory
		event-item is {@gPiston}:
			cancel event
			remove all {@gPiston} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gPiston} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
		event-item is {@gBoat}:
			cancel event
			remove all {@gBoat} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gBoat} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
		event-item is {@gCart}:
			cancel event
			remove all {@gCart} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gCart} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
		event-item is {@gFirework}:
			cancel event
			remove all {@gFirework} from player's inventory
			give 1 stone to player
			give 1 grass block to player
			give 1 dirt to player
			give 1 {@gFirework} to player
			remove all stone from player's inventory
			remove all grass block from player's inventory
			remove all dirt from player's inventory
			
on death:
	player is in "world":
		remove all {@gHelp} from drops
		remove all {@gWorlds} from drops
		remove all {@gFly} from drops
		remove all {@gToybox} from drops
		remove all {@gBoat} from drops
		remove all {@gCart} from drops
		remove all {@gFirework} from drops
		remove all {@gPiston} from drops
		remove all {@gEffectmachine} from drops
		
command /worlds [<text>]:
	permission: obam.free
	trigger:
		#world is "Death-hub"
		world is "world":
			argument is not set:
				player has permission "obam.admin":
					send "&eOpening the &fWorld &3Viewer &e. . ."
					show "s;1;{@dSkyblock};s;3;{@dKitpvp};s;5;{@dFronts};s;7;{@dWtfronts};s;9;{@dGarage}" with 1 row named "&dWorld &3Viewer" to player
					stop
				player has permission "obam.smod":
					send "&eOpening the &fWorld &3Viewer &e. . ."
					show "s;1;{@dSkyblock};s;3;{@dKitpvp};s;5;{@dFronts};s;7;{@dWtfronts};s;9;{@dGarage}" with 1 row named "&dWorld &3Viewer" to player
					stop
				player has permission "obam.mod":
					send "&eOpening the &fWorld &3Viewer &e. . ."
					show "s;1;{@dSkyblock};s;3;{@dKitpvp};s;5;{@dFronts};s;7;{@dWtfronts};s;9;{@dGarage}" with 1 row named "&dWorld &3Viewer" to player
					stop
				player has permission "obam.mechanic":
					send "&eOpening the &fWorld &3Viewer &e. . ."
					show "s;1;{@dSkyblock};s;3;{@dKitpvp};s;5;{@dFronts};s;7;{@dWtfronts};s;9;{@dGarage}" with 1 row named "&dWorld &3Viewer" to player
					stop
				send "&eOpening the &fWorld &3Viewer &e. . ."
				show "s;2;{@dSkyblock};s;4;{@dKitpvp};s;6;{@dFronts};s;8;{@dWtfronts}" with 1 row named "&dWorld &3Viewer" to player
				stop
			argument is "survival":
				send "&eYou are being summoned to Fronts." to player
				make player execute command "/transfer survival"
			argument is "wtf":
				send "&eYou are being summoned to WTF." to player
				make player execute command "/transfer curtain"
			argument is "skyblock":
				send "&eYou are being summoned to SkyBlock." to player
				execute console command "mv tp %player% skyworld"
			argument is "kit":
				send "&eYou are being summoned to KitPVP." to player
				execute console command "mv tp %player% kitpvpkillingfields"
			argument is "garage":
				send "&eYou are being summoned to Garage." to player
				make player execute command "/transfer garage"
			
command /flight:
	trigger:
		#world is "Death-hub"
		world is "world":
			{fly.hub.%player%} is not set:
				set {fly.hub.%player%} to true
				set player's fly state to true
				send "&aYou can fly!" to player
				stop
			{fly.hub.%player%} is true:
				set {fly.hub.%player%} to false
				set player's fly state to false
				send "&cYou can no longer fly!" to player
				stop
			{fly.hub.%player%} is false:
				set {fly.hub.%player%} to true
				set player's fly state to true
				send "&aYou can fly!" to player
				stop
				
command /transfer [<text>]:
	trigger:
		#world is "Death-hub"
		world is "world":
			connect player to "%argument%"
		
command /toy [<text>]:
	trigger:
		player is in "world":
			argument is not set:
				send "&eCorrect Usage: /toy shop" to player
				stop
			argument is "shop":
				set {_amount.%player%} to player's balance
				send "&f&eCurrent Balance: &f%{_amount.%player%}%" to player
				wait 1 second
				send "&eEntering the &2Toy &9Shop &e. . ." to player
				if {db_toyshop.firework.%player%} is true:
					if {db_toyshop.piston.%player%} is true:	
						show "s;3;{@bFirework};s;7;{@bPiston}" with 1 row named "&2Toy &9Shop" to player
						stop
				if {db_toyshop.firework.%player%} is true:
					if {db_toyshop.piston.%player%} is false:	
						show "s;3;{@bFirework};s;7;{@uPiston}" with 1 row named "&2Toy &9Shop" to player
						stop
				if {db_toyshop.firework.%player%} is false:
					if {db_toyshop.piston.%player%} is true:	
						show "s;3;{@uFirework};s;7;{@bPiston}" with 1 row named "&2Toy &9Shop" to player
						stop
				show "s;3;{@uFirework};s;7;{@uPiston}" with 1 row named "&2Toy &9Shop" to player
				stop
			argument is "firework":
				wait 1 second
				make player execute command "/buy firework"
				stop
			argument is "piston":
				wait 1 second
				make player execute command "/buy piston"
				stop
				
command /effect [<text>]:
	trigger:
		player is in "world":
			argument is not set:
				send "&eCorrect Usage: /effect shop" to player
				stop
			argument is "shop":
				set {_amount.%player%} to player's balance
				send "&f&eCurrent Balance: &f%{_amount.%player%}%" to player
				wait 1 second
				send "&eEntering the &9Effect &2Shop &e. . ." to player
				if {db_effectshop.effect.%player%} is true:
					show "s;3;{@bEffect};s;7;{@dShop}" with 1 row named "&9Effect &2Shop" to player
					stop
				if {db_effectshop.effect.%player%} is false:
					show "s;3;{@uEffect};s;7;{@dShop}" with 1 row named "&9Effect &2Shop" to player
					stop
			argument is "magic":
				wait 1 second
				make player execute command "/buy effect"
				stop
			argument is "disguise":
				set {_amount.%player%} to player's balance
				send "&f&eCurrent Balance: &f%{_amount.%player%}%" to player
				wait 1 second
				send "&eEntering the &9Disguise &2Shop &e. . ." to player
				set {_increment.closet.%player%} to 1
				if {db_effectshop.disguises.creeper.%player%} is true:
					set {_shop.d1.%player%} to ""
				if {db_effectshop.disguises.creeper.%player%} is false:
					set {_slot.d1.%player%} to {_increment.closet.%player%}
					set {_shop.d1.%player%} to "s;%{_slot.d1.%player%}%;i;creeper spawn egg;n;&6Creeper;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 1;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}						
				if {db_effectshop.disguises.skeleton.%player%} is true:
					set {_shop.d2.%player%} to ""
				if {db_effectshop.disguises.skeleton.%player%} is false:
					set {_slot.d2.%player%} to {_increment.closet.%player%}
					set {_shop.d2.%player%} to "s;%{_slot.d2.%player%}%;i;skeleton spawn egg;n;&6Skeleton;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 2;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.spider.%player%} is true:
					set {_shop.d3.%player%} to ""						
				if {db_effectshop.disguises.spider.%player%} is false:
					set {_slot.d3.%player%} to {_increment.closet.%player%}
					set {_shop.d3.%player%} to "s;%{_slot.d3.%player%}%;i;spider spawn egg;n;&6Spider;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 3;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.zombie.%player%} is true:
					set {_shop.d4.%player%} to ""						
				if {db_effectshop.disguises.zombie.%player%} is false:
					set {_slot.d4.%player%} to {_increment.closet.%player%}
					set {_shop.d4.%player%} to "s;%{_slot.d4.%player%}%;i;zombie spawn egg;n;&6Zombie;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 4;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.slime.%player%} is true:
					set {_shop.d5.%player%} to ""						
				if {db_effectshop.disguises.slime.%player%} is false:
					set {_slot.d5.%player%} to {_increment.closet.%player%}
					set {_shop.d5.%player%} to "s;%{_slot.d5.%player%}%;i;slime spawn egg;n;&6Slime;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 5;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.ghast.%player%} is true:
					set {_shop.d6.%player%} to ""						
				if {db_effectshop.disguises.ghast.%player%} is false:
					set {_slot.d6.%player%} to {_increment.closet.%player%}
					set {_shop.d6.%player%} to "s;%{_slot.d6.%player%}%;i;ghast spawn egg;n;&6Ghast;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 6;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.zombiepigman.%player%} is true:
					set {_shop.d7.%player%} to ""						
				if {db_effectshop.disguises.zombiepigman.%player%} is false:
					set {_slot.d7.%player%} to {_increment.closet.%player%}
					set {_shop.d7.%player%} to "s;%{_slot.d7.%player%}%;i;zombie pigman spawn egg;n;&6Zombie Pigman;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 7;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.enderman.%player%} is true:
					set {_shop.d8.%player%} to ""						
				if {db_effectshop.disguises.enderman.%player%} is false:
					set {_slot.d8.%player%} to {_increment.closet.%player%}
					set {_shop.d8.%player%} to "s;%{_slot.d8.%player%}%;i;enderman spawn egg;n;&6Enderman;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 8;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.cavespider.%player%} is true:
					set {_shop.d9.%player%} to ""						
				if {db_effectshop.disguises.cavespider.%player%} is false:
					set {_slot.d9.%player%} to {_increment.closet.%player%}
					set {_shop.d9.%player%} to "s;%{_slot.d9.%player%}%;i;cave spider spawn egg;n;&6Cave Spider;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 9;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.silverfish.%player%} is true:
					set {_shop.d10.%player%} to ""
				if {db_effectshop.disguises.silverfish.%player%} is false:
					set {_slot.d10.%player%} to {_increment.closet.%player%}
					set {_shop.d10.%player%} to "s;%{_slot.d10.%player%}%;i;silverfish spawn egg;n;&6Silverfish;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 10;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}						
				if {db_effectshop.disguises.blaze.%player%} is true:
					set {_shop.d11.%player%} to ""
				if {db_effectshop.disguises.blaze.%player%} is false:
					set {_slot.d11.%player%} to {_increment.closet.%player%}
					set {_shop.d11.%player%} to "s;%{_slot.d11.%player%}%;i;blaze spawn egg;n;&6Blaze;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 11;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.magmacube.%player%} is true:
					set {_shop.d12.%player%} to ""						
				if {db_effectshop.disguises.magmacube.%player%} is false:
					set {_slot.d12.%player%} to {_increment.closet.%player%}
					set {_shop.d12.%player%} to "s;%{_slot.d12.%player%}%;i;magma cube spawn egg;n;&6Magma Cube;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 12;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.bat.%player%} is true:
					set {_shop.d13.%player%} to ""						
				if {db_effectshop.disguises.bat.%player%} is false:
					set {_slot.d13.%player%} to {_increment.closet.%player%}
					set {_shop.d13.%player%} to "s;%{_slot.d13.%player%}%;i;bat spawn egg;n;&6Bat;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 13;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}				
				if {db_effectshop.disguises.witch.%player%} is true:
					set {_shop.d14.%player%} to ""						
				if {db_effectshop.disguises.witch.%player%} is false:
					set {_slot.d14.%player%} to {_increment.closet.%player%}
					set {_shop.d14.%player%} to "s;%{_slot.d14.%player%}%;i;witch spawn egg;n;&6Witch;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 14;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}			
				if {db_effectshop.disguises.pig.%player%} is true:
					set {_shop.d15.%player%} to ""						
				if {db_effectshop.disguises.pig.%player%} is false:
					set {_slot.d15.%player%} to {_increment.closet.%player%}
					set {_shop.d15.%player%} to "s;%{_slot.d15.%player%}%;i;pig spawn egg;n;&6Pig;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 15;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.sheep.%player%} is true:
					set {_shop.d16.%player%} to ""						
				if {db_effectshop.disguises.sheep.%player%} is false:
					set {_slot.d16.%player%} to {_increment.closet.%player%}
					set {_shop.d16.%player%} to "s;%{_slot.d16.%player%}%;i;sheep spawn egg;n;&6Sheep;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 16;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.cow.%player%} is true:
					set {_shop.d17.%player%} to ""						
				if {db_effectshop.disguises.cow.%player%} is false:
					set {_slot.d17.%player%} to {_increment.closet.%player%}
					set {_shop.d17.%player%} to "s;%{_slot.d17.%player%}%;i;cow spawn egg;n;&6Cow;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 17;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}		
				if {db_effectshop.disguises.chicken.%player%} is true:
					set {_shop.d18.%player%} to ""						
				if {db_effectshop.disguises.chicken.%player%} is false:
					set {_slot.d18.%player%} to {_increment.closet.%player%}
					set {_shop.d18.%player%} to "s;%{_slot.d18.%player%}%;i;chicken spawn egg;n;&6Chicken;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 18;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}
				if {db_effectshop.disguises.squid.%player%} is true:
					set {_shop.d19.%player%} to ""						
				if {db_effectshop.disguises.squid.%player%} is false:
					set {_slot.d19.%player%} to {_increment.closet.%player%}
					set {_shop.d19.%player%} to "s;%{_slot.d19.%player%}%;i;squid spawn egg;n;&6Squid;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 19;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}				
				if {db_effectshop.disguises.wolf.%player%} is true:
					set {_shop.d20.%player%} to ""						
				if {db_effectshop.disguises.wolf.%player%} is false:
					set {_slot.d20.%player%} to {_increment.closet.%player%}
					set {_shop.d20.%player%} to "s;%{_slot.d20.%player%}%;i;wolf spawn egg;n;&6Wolf;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 20;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}		
				if {db_effectshop.disguises.mooshroom.%player%} is true:
					set {_shop.d21.%player%} to ""									
				if {db_effectshop.disguises.mooshroom.%player%} is false:
					set {_slot.d21.%player%} to {_increment.closet.%player%}
					set {_shop.d21.%player%} to "s;%{_slot.d21.%player%}%;i;mooshroom spawn egg;n;&6Mooshroom;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 21;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.ocelot.%player%} is true:
					set {_shop.d22.%player%} to ""									
				if {db_effectshop.disguises.ocelot.%player%} is false:
					set {_slot.d22.%player%} to {_increment.closet.%player%}
					set {_shop.d22.%player%} to "s;%{_slot.d22.%player%}%;i;ocelot spawn egg;n;&6Ocelot;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 22;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.horse.%player%} is true:
					set {_shop.d23.%player%} to ""									
				if {db_effectshop.disguises.horse.%player%} is false:
					set {_slot.d23.%player%} to {_increment.closet.%player%}
					set {_shop.d23.%player%} to "s;%{_slot.d23.%player%}%;i;horse spawn egg;n;&6Horse;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 23;"
					if {_increment.closet.%player%} is 52:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 50:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 48:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 46:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 45:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 43:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 41:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 39:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 37:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 36:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 34:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 32:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 30:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 28:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 27:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 25:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 23:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 21:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 19:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 18:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 16:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 14:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 12:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 10:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 9:
						add 1 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 7:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 5:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 3:
						add 2 to {_increment.closet.%player%}
					if {_increment.closet.%player%} is 1:
						add 2 to {_increment.closet.%player%}	
				if {db_effectshop.disguises.villager.%player%} is true:
					set {_shop.d24.%player%} to ""			
				if {db_effectshop.disguises.villager.%player%} is false:
					set {_slot.d24.%player%} to {_increment.closet.%player%}
					set {_shop.d24.%player%} to "s;%{_slot.d24.%player%}%;i;villager spawn egg;n;&6Villager;l;&3Not Purchased|| ||&aPrice: 10,000 tickets||&5Click to Buy.;c;sudo %player% effect 24"
					#if more are added - add a semicolon at the end of the variable
					#add more incrementation values here later for more releases
				show "%{_shop.d1.%player%}%%{_shop.d2.%player%}%%{_shop.d3.%player%}%%{_shop.d4.%player%}%%{_shop.d5.%player%}%%{_shop.d6.%player%}%%{_shop.d7.%player%}%%{_shop.d8.%player%}%%{_shop.d9.%player%}%%{_shop.d10.%player%}%%{_shop.d11.%player%}%%{_shop.d12.%player%}%%{_shop.d13.%player%}%%{_shop.d14.%player%}%%{_shop.d15.%player%}%%{_shop.d16.%player%}%%{_shop.d17.%player%}%%{_shop.d18.%player%}%%{_shop.d19.%player%}%%{_shop.d20.%player%}%%{_shop.d21.%player%}%%{_shop.d22.%player%}%%{_shop.d23.%player%}%%{_shop.d24.%player%}%" with 6 rows named "&3Disguise &2Shop" to player
				stop
			
command /buy [<text>]:
	trigger:
		player is in "world":
			argument is not set:
				send "&eCorrect Usage: &F/buy (item)" to player
				send "&eFor a list of current items type &f/buy list" to player
				stop
			argument is "list":
				send "&eBuyable Toy List:" to player
				send "&f-Player Pusher: &a2,500 tickets" to player
				send "&f-OBAM Firework: &a5,000 tickets" to player
				send "" to player
				send "&3Buyable Effects List:" to player
				send "&9-Unstable Pack: &a2,500 tickets" to player
				send "&9-Mob Disguises: &a5,000 tickets" to player
				stop
			argument is "piston":
				if {db_toyshop.piston.%player%} is true:
					send "&6Player&fPusher &ehas already been bought." to player
					stop
				if {db_toyshop.piston.%player%} is false:
					set {_amount.%player%} to player's balance
					if {_amount.%player%} is less than 2500:
						send "&cYou do not have enough tickets for that!" to player
						stop
					subtract 2500 from player's balance
					set {_amount.%player%} to player's balance
					send "&aYou have just purchased the &bPlayerPusher &afrom the Toy Shop!" to player
					send "&aYour new balance is now: &e%{_amount.%player%}%." to player
					set {db_toyshop.piston.%player%} to true
					log "%player% bought PlayerPusher for 2,500 tickets at %now%" to "/shop/toys/PlayerPusher.log"
					stop
			argument is "firework":
				if {db_toyshop.firework.%player%} is true:
					send "&6OBAM&fFirework &ehas already been bought." to player
					stop
				if {db_toyshop.firework.%player%} is false:
					set {_amount.%player%} to player's balance
					if {_amount.%player%} is less than 5000:
						send "&cYou do not have enough tickets for that!" to player
						stop
					subtract 5000 from player's balance
					set {_amount.%player%} to player's balance
					send "&aYou have just purchased the &bOBAMFirework &afrom the Toy Shop!" to player
					send "&aYour new balance is now: &e%{_amount.%player%}%." to player
					set {db_toyshop.firework.%player%} to true
					log "%player% bought ObamFirework for 5,000 tickets at %now%" to "/shop/toys/ObamFirework.log"
					stop
			argument is "effect":
				if {db_effectshop.effect.%player%} is true:
					send "&6Unstable &fGases &ehave already been bought." to player
					stop
				if {db_effectshop.effect.%player%} is false:
					set {_amount.%player%} to player's balance
					if {_amount.%player%} is less than 5000:
						send "&cYou do not have enough tickets for that!" to player
						stop
					subtract 5000 from player's balance
					set {_amount.%player%} to player's balance
					send "&aYou have just purchased &6Unstable &fGases &afrom the Effect Shop!" to player
					send "&aYour new balance is now: &e%{_amount.%player%}%." to player
					set {db_effectshop.effect.%player%} to true
					log "%player% bought Unstable Gases for 5,000 tickets at %now%" to "/shop/effects/UnstableGases.log"
					stop
			argument is "disguise":
				if {db_effectshop.disguise.%player%} is true:
					send "&6Disguise &fCloset &ehas already been bought." to player
					stop
				if {db_effectshop.disguise.%player%} is false:
					set {_amount.%player%} to player's balance
					if {_amount.%player%} is less than 2500:
						send "&cYou do not have enough tickets for that!" to player
						stop
					subtract 2500 from player's balance
					set {_amount.%player%} to player's balance
					send "&aYou have just purchased the &6Disguise &fCloset &afrom the Effect Shop!" to player
					send "&aYour new balance is now: &e%{_amount.%player%}%." to player
					set {db_effectshop.disguise.%player%} to true
					log "%player% bought the Disguise Closet for 2,500 tickets at %now%" to "/shop/effects/DisguiseCloset.log"
					stop
						
command /toybox [<text>]:
	trigger:
		#player is in "Death-hub":
		player is in "world":
			argument is not set:
				if {db_toyshop.firework.%player%} is false:
					if {db_toyshop.piston.%player%} is true:
						if {toybox.boat.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@eBoat};s;4;{@dCart};s;6;{@nFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						if {toybox.cart.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@dBoat};s;4;{@eCart};s;6;{@nFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						if {toybox.piston.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@dBoat};s;4;{@dCart};s;6;{@nFirework};s;8;{@ePiston}" with 1 row named "&2Toy &9Box" to player
							stop
						send "&eOpening the majestical &2Toy &9Box &e. . ." to player
						show "s;2;{@dBoat};s;4;{@dCart};s;6;{@nFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
						stop
					if {db_toyshop.piston.%player%} is false:
						if {toybox.boat.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@eBoat};s;4;{@dCart};s;6;{@nFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						if {toybox.cart.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@dBoat};s;4;{@eCart};s;6;{@nFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						send "&eOpening the majestical &2Toy &9Box &e. . ." to player
						show "s;2;{@dBoat};s;4;{@dCart};s;6;{@nFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
						stop
				if {db_toyshop.piston.%player%} is false:
					if {db_toyshop.firework.%player%} is true:
						if {toybox.boat.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@eBoat};s;4;{@dCart};s;6;{@dFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						if {toybox.cart.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@dBoat};s;4;{@eCart};s;6;{@dFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						if {toybox.firework.%player%} is 1:
							send "&eOpening the majestical &2Toy &9Box &e. . ." to player
							show "s;2;{@dBoat};s;4;{@dCart};s;6;{@eFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
							stop
						send "&eOpening the majestical &2Toy &9Box &e. . ." to player
						show "s;2;{@dBoat};s;4;{@dCart};s;6;{@dFirework};s;8;{@nPiston}" with 1 row named "&2Toy &9Box" to player
						stop
				if {toybox.boat.%player%} is 1:
					send "&eOpening the majestical &2Toy &9Box &e. . ." to player
					show "s;2;{@eBoat};s;4;{@dCart};s;6;{@dFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
					stop
				if {toybox.cart.%player%} is 1:
					send "&eOpening the majestical &2Toy &9Box &e. . ." to player
					show "s;2;{@dBoat};s;4;{@eCart};s;6;{@dFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
					stop
				if {toybox.firework.%player%} is 1:
					send "&eOpening the majestical &2Toy &9Box &e. . ." to player
					show "s;2;{@dBoat};s;4;{@dCart};s;6;{@eFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
					stop
				if {toybox.piston.%player%} is 1:
					send "&eOpening the majestical &2Toy &9Box &e. . ." to player
					show "s;2;{@dBoat};s;4;{@dCart};s;6;{@dFirework};s;8;{@ePiston}" with 1 row named "&2Toy &9Box" to player
					stop
				send "&eOpening the majestical &2Toy &9Box &e. . ." to player
				show "s;2;{@dBoat};s;4;{@dCart};s;6;{@dFirework};s;8;{@dPiston}" with 1 row named "&2Toy &9Box" to player
				stop
			argument is "boat":
				make player execute command "/boat"
			argument is "cart":
				make player execute command "/cart"
			argument is "firework":
				make player execute command "/firework"
			argument is "piston":
				make player execute command "/piston"
				
command /effectmachine [<text>]:
	trigger:
		player is in "world":
			argument is not set:
				if {db_effectshop.effect.%player%} is false:
					send "&ePowering the &2Effect &3Machine &e. . ." to player
					show "s;1;{@nEffect};s;5;{@dDisguise};s;9;{@eShop}" with 1 row named "&2Effect &3Machine" to player
					stop
				if {db_effectshop.effect.%player%} is true:
					if {effects.magic.%player%} is 1:
						send "&ePowering the &2Effect &3Machine &e. . ." to player
						show "s;1;{@eEffect};s;5;{@dDisguise};s;9;{@eShop}" with 1 row named "&2Effect &3Machine" to player
						stop
					if {effects.magic.%player%} is 0:
						send "&ePowering the &2Effect &3Machine &e. . ." to player
						show "s;1;{@dEffect};s;5;{@dDisguise};s;9;{@eShop}" with 1 row named "&2Effect &3Machine" to player
			argument is "disguise":
				send "&eUnlocking your closet. . ." to player
				wait 1 second
				make player execute command "/disguiseset"
			argument is "magic":
				make player execute command "/magic default"
				
command /magic [<text>]:
	trigger:
		player is in "world":
			if {db_effectshop.effect.%player%} is true:
				if argument is "default":
					if {effects.magic.%player%} is 0:
						set {effects.magic.%player%} to 1
						send "&fYou are now &cunstable&f." to player
						make player execute command "/magic effect"
						stop
					if {effects.magic.%player%} is 1:
						set {effects.magic.%player%} to 0
						send "&fYou are now &astable&f." to player
						stop
				if argument is "effect":
					if {effects.magic.%player%} is 1:
						set {_magic.loc.%player%} to location of player
						spawn 100 of red dust data 1 offset with 1, 1, 1 at {_magic.loc.%player%}
						wait 2 seconds
						make player execute command "/magic effect"
			if {db_effectshop.effect.%player%} is false:
				send "&eSorry, You have not unlocked this yet." to player
				stop
			
command /boat:
	trigger:
		player is in "world":
			if {toybox.boat.%player%} is 0:
				if {cartstop.%player%} is true:
					loop all entities in player's world:
						if loop-entity is a minecart:
							if name of loop-entity is "&3%player%'s &fCart":
								delete loop-entity
				if player has {@gFirework} in his inventory:
					remove all {@gFirework} from player's inventory
					set {toybox.firework.%player%} to 0
				if player has {@gPiston} in his inventory:
					remove all {@gPiston} from player's inventory
					set {toybox.piston.%player%} to 0
				if player has {@gCart} in his inventory:
					remove all {@gCart} from player's inventory
					set {toybox.cart.%player%} to 0
					set {cartstop.%player%} to false
				if {boatstop.%player%} is true:
					send "You already have a boat out." to player
					stop
				give 1 stone to player
				give 1 grass block to player
				give 1 dirt to player
				give 1 {@gBoat} to player
				remove all stone from player's inventory
				remove all grass block from player's inventory
				remove all dirt from player's inventory
				set {toybox.boat.%player%} to 1
				set {boatstop.%player%} to true
				send "You have received a boat." to player
				stop
			if {toybox.boat.%player%} is 1:
				if {boatstop.%player%} is true:
					loop all entities in player's world:
						if loop-entity is a boat:
							if name of loop-entity is "&3%player%'s &fBoat":
								delete loop-entity
				if player has {@gBoat} in his inventory:
					remove all {@gBoat} from player's inventory
					set {toybox.boat.%player%} to 0
					set {boatstop.%player%} to false
					stop
					
command /cart:
	trigger:
		player is in "world":
			if {toybox.cart.%player%} is 0:
				if {boatstop.%player%} is true:
					loop all entities in player's world:
						if loop-entity is a boat:
							if name of loop-entity is "&3%player%'s &fBoat":
								delete loop-entity
				if player has {@gFirework} in his inventory:
					remove all {@gFirework} from player's inventory
					set {toybox.firework.%player%} to 0
				if player has {@gPiston} in his inventory:
					remove all {@gPiston} from player's inventory
					set {toybox.piston.%player%} to 0
				if player has {@gBoat} in his inventory:
					remove all {@gBoat} from player's inventory
					set {toybox.boat.%player%} to 0
					set {boatstop.%player%} to false
				if {cartstop.%player%} is true:
					send "You already have a minecart out." to player
					stop
				give 1 stone to player
				give 1 grass block to player
				give 1 dirt to player
				give 1 {@gCart} to player
				remove all stone from player's inventory
				remove all grass block from player's inventory
				remove all dirt from player's inventory
				set {toybox.cart.%player%} to 1
				set {cartstop.%player%} to true
				send "You have received a minecart." to player
				stop
			if {toybox.cart.%player%} is 1:
				if {cartstop.%player%} is true:
					loop all entities in player's world:
						if loop-entity is a minecart:
							if name of loop-entity is "&3%player%'s &fCart":
								delete loop-entity
				if player has {@gCart} in his inventory:
					remove all {@gCart} from player's inventory
					set {toybox.cart.%player%} to 0
					set {cartstop.%player%} to false
					stop
					
command /firework:
	trigger:
		player is in "world":
			if {db_toyshop.firework.%player%} is true:
				if {toybox.firework.%player%} is 0:
					if {boatstop.%player%} is true:
						loop all entities in player's world:
							if loop-entity is a boat:
								if name of loop-entity is "&3%player%'s &fBoat":
									delete loop-entity
					if {cartstop.%player%} is true:
						loop all entities in player's world:
							if loop-entity is a minecart:
								if name of loop-entity is "&3%player%'s &fCart":
									delete loop-entity
					if player has {@gBoat} in his inventory:
						remove all {@gBoat} from player's inventory
						set {toybox.boat.%player%} to 0
						set {boatstop.%player%} to false
					if player has {@gCart} in his inventory:
						remove all {@gCart} from player's inventory
						set {toybox.cart.%player%} to 0
						set {cartstop.%player%} to false
					if player has {@gPiston} in his inventory:
						remove all {@gPiston} from player's inventory
						set {toybox.piston.%player%} to 0
					give 1 stone to player
					give 1 grass block to player
					give 1 dirt to player
					give 1 {@gFirework} to player
					remove all stone from player's inventory
					remove all grass block from player's inventory
					remove all dirt from player's inventory
					set {toybox.firework.%player%} to 1
					send "You have received an OBAM Firework" to player
					stop
				if {toybox.firework.%player%} is 1:
					if player has {@gFirework} in his inventory:
						remove all {@gFirework} from player's inventory
						set {toybox.firework.%player%} to 0
						stop
			send "&eSorry, You have not unlocked this yet." to player
			stop
					
command /piston:
	trigger:
		player is in "world":
			if {db_toyshop.piston.%player%} is true:
				if {toybox.piston.%player%} is 0:
					if {boatstop.%player%} is true:
						loop all entities in player's world:
							if loop-entity is a boat:
								if name of loop-entity is "&3%player%'s &fBoat":
									delete loop-entity
					if {cartstop.%player%} is true:
						loop all entities in player's world:
							if loop-entity is a minecart:
								if name of loop-entity is "&3%player%'s &fCart":
									delete loop-entity
					if player has {@gBoat} in his inventory:
						remove all {@gBoat} from player's inventory
						set {toybox.boat.%player%} to 0
						set {boatstop.%player%} to false
					if player has {@gCart} in his inventory:
						remove all {@gCart} from player's inventory
						set {toybox.cart.%player%} to 0
						set {cartstop.%player%} to false
					if player has {@gFirework} in his inventory:
						remove all {@gFirework} from player's inventory
						set {toybox.firework.%player%} to 0
					give 1 stone to player
					give 1 grass block to player
					give 1 dirt to player
					give 1 {@gPiston} to player
					remove all stone from player's inventory
					remove all grass block from player's inventory
					remove all dirt from player's inventory
					set {toybox.piston.%player%} to 1
					send "You have received a player pusher" to player
					stop
				if {toybox.piston.%player%} is 1:
					if player has {@gPiston} in his inventory:
						remove all {@gPiston} from player's inventory
						set {toybox.piston.%player%} to 0
						stop
			send "&eSorry, You have not unlocked this yet." to player
			stop
			
command /disguiseset [<text>]:
	trigger:
		if argument is not set:
		#alternative: light gray stained glass pane
		#for misa etc: gray stained glass pane
		#until shiny use: ender portal
			send "&eOpening up your closet. . ." to player
			if {db_effectshop.disguises.creeper.%player%} is true:
				if {effects.disguises.creeper.%player%} is 0:
					set {_temp.d1.%player%} to "s;1;i;creeper spawn egg;n;&6Creeper;l;&7Currently &aEnabled;c;sudo %player% disguiseset creeper"
				if {effects.disguises.creeper.%player%} is 1:
					set {_temp.d1.%player%} to "s;1;i;creeper spawn egg;n;&6Creeper;l;&7Currently &cDisabled;c;sudo %player% disguiseset creeper"
			if {db_effectshop.disguises.creeper.%player%} is false:
				set {_temp.d1.%player%} to "s;1;i;ender portal;n;&6Creeper;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.skeleton.%player%} is true:
				if {effects.disguises.skeleton.%player%} is 0:
					set {_temp.d2.%player%} to "s;3;i;skeleton spawn egg;n;&6Skeleton;l;&7Currently &aEnabled;c;sudo %player% disguiseset skeleton"
				if {effects.disguises.skeleton.%player%} is 1:
					set {_temp.d2.%player%} to "s;3;i;skeleton spawn egg;n;&6Skeleton;l;&7Currently &cDisabled;c;sudo %player% disguiseset skeleton"
			if {db_effectshop.disguises.skeleton.%player%} is false:
				set {_temp.d2.%player%} to "s;3;i;ender portal;n;&6Skeleton;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"				
			if {db_effectshop.disguises.spider.%player%} is true:
				if {effects.disguises.spider.%player%} is 0:
					set {_temp.d3.%player%} to "s;5;i;spider spawn egg;n;&6Spider;l;&7Currently &aEnabled;c;sudo %player% disguiseset spider"
				if {effects.disguises.spider.%player%} is 1:
					set {_temp.d3.%player%} to "s;5;i;spider spawn egg;n;&6Spider;l;&7Currently &cDisabled;c;sudo %player% disguiseset spider"
			if {db_effectshop.disguises.spider.%player%} is false:
				set {_temp.d3.%player%} to "s;5;i;ender portal;n;&6Spider;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"		
			if {db_effectshop.disguises.zombie.%player%} is true:
				if {effects.disguises.zombie.%player%} is 0:
					set {_temp.d4.%player%} to "s;7;i;zombie spawn egg;n;&6Zombie;l;&7Currently &aEnabled;c;sudo %player% disguiseset zombie"
				if {effects.disguises.zombie.%player%} is 1:
					set {_temp.d4.%player%} to "s;7;i;zombie spawn egg;n;&6Zombie;l;&7Currently &cDisabled;c;sudo %player% disguiseset zombie"
			if {db_effectshop.disguises.zombie.%player%} is false:
				set {_temp.d4.%player%} to "s;7;i;ender portal;n;&6Zombie;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"		
			if {db_effectshop.disguises.slime.%player%} is true:
				if {effects.disguises.slime.%player%} is 0:
					set {_temp.d5.%player%} to "s;9;i;slime spawn egg;n;&6Slime;l;&7Currently &aEnabled;c;sudo %player% disguiseset slime"
				if {effects.disguises.slime.%player%} is 1:
					set {_temp.d5.%player%} to "s;9;i;slime spawn egg;n;&6Slime;l;&7Currently &cDisabled;c;sudo %player% disguiseset slime"
			if {db_effectshop.disguises.slime.%player%} is false:
				set {_temp.d5.%player%} to "s;9;i;ender portal;n;&6Slime;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"	
			if {db_effectshop.disguises.ghast.%player%} is true:
				if {effects.disguises.ghast.%player%} is 0:
					set {_temp.d6.%player%} to "s;10;i;ghast spawn egg;n;&6Ghast;l;&7Currently &aEnabled;c;sudo %player% disguiseset ghast"
				if {effects.disguises.ghast.%player%} is 1:
					set {_temp.d6.%player%} to "s;10;i;ghast spawn egg;n;&6Ghast;l;&7Currently &cDisabled;c;sudo %player% disguiseset ghast"
			if {db_effectshop.disguises.ghast.%player%} is false:
				set {_temp.d6.%player%} to "s;10;i;ender portal;n;&6Ghast;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.zombiepigman.%player%} is true:
				if {effects.disguises.zombiepigman.%player%} is 0:
					set {_temp.d7.%player%} to "s;12;i;zombie pigman spawn egg;n;&6Zombie Pigman;l;&7Currently &aEnabled;c;sudo %player% disguiseset zombiepigman"
				if {effects.disguises.zombiepigman.%player%} is 1:
					set {_temp.d7.%player%} to "s;12;i;zombie pigman spawn egg;n;&6Zombie Pigman;l;&7Currently &cDisabled;c;sudo %player% disguiseset zombiepigman"
			if {db_effectshop.disguises.zombiepigman.%player%} is false:
				set {_temp.d7.%player%} to "s;12;i;ender portal;n;&6Zombie Pigman;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.enderman.%player%} is true:
				if {effects.disguises.enderman.%player%} is 0:
					set {_temp.d8.%player%} to "s;14;i;enderman spawn egg;n;&6Enderman;l;&7Currently &aEnabled;c;sudo %player% disguiseset enderman"
				if {effects.disguises.enderman.%player%} is 1:
					set {_temp.d8.%player%} to "s;14;i;enderman spawn egg;n;&6Enderman;l;&7Currently &cDisabled;c;sudo %player% disguiseset enderman"
			if {db_effectshop.disguises.enderman.%player%} is false:
				set {_temp.d8.%player%} to "s;14;i;ender portal;n;&6Enderman;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.cavespider.%player%} is true:
				if {effects.disguises.cavespider.%player%} is 0:
					set {_temp.d9.%player%} to "s;16;i;cave spider spawn egg;n;&6Cave Spider;l;&7Currently &aEnabled;c;sudo %player% disguiseset cavespider"
				if {effects.disguises.cavespider.%player%} is 1:
					set {_temp.d9.%player%} to "s;16;i;cave spider spawn egg;n;&6Cave Spider;l;&7Currently &cDisabled;c;sudo %player% disguiseset cavespider"
			if {db_effectshop.disguises.cavespider.%player%} is false:
				set {_temp.d9.%player%} to "s;16;i;ender portal;n;&6Cave Spider;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.silverfish.%player%} is true:
				if {effects.disguises.silverfish.%player%} is 0:
					set {_temp.d10.%player%} to "s;18;i;silverfish spawn egg;n;&6Silverfish;l;&7Currently &aEnabled;c;sudo %player% disguiseset silverfish"
				if {effects.disguises.silverfish.%player%} is 1:
					set {_temp.d10.%player%} to "s;18;i;silverfish spawn egg;n;&6Silverfish;l;&7Currently &cDisabled;c;sudo %player% disguiseset silverfish"
			if {db_effectshop.disguises.silverfish.%player%} is false:
				set {_temp.d10.%player%} to "s;18;i;ender portal;n;&6Silverfish;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.blaze.%player%} is true:
				if {effects.disguises.blaze.%player%} is 0:
					set {_temp.d11.%player%} to "s;19;i;blaze spawn egg;n;&6Blaze;l;&7Currently &aEnabled;c;sudo %player% disguiseset blaze"
				if {effects.disguises.blaze.%player%} is 1:
					set {_temp.d11.%player%} to "s;19;i;blaze spawn egg;n;&6Blaze;l;&7Currently &cDisabled;c;sudo %player% disguiseset blaze"
			if {db_effectshop.disguises.blaze.%player%} is false:
				set {_temp.d11.%player%} to "s;19;i;ender portal;n;&6Blaze;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.magmacube.%player%} is true:
				if {effects.disguises.magmacube.%player%} is 0:
					set {_temp.d12.%player%} to "s;21;i;magma cube spawn egg;n;&6Magma Cube;l;&7Currently &aEnabled;c;sudo %player% disguiseset magmacube"
				if {effects.disguises.magmacube.%player%} is 1:
					set {_temp.d12.%player%} to "s;21;i;magma cube spawn egg;n;&6Magma Cube;l;&7Currently &cDisabled;c;sudo %player% disguiseset magmacube"
			if {db_effectshop.disguises.magmacube.%player%} is false:
				set {_temp.d12.%player%} to "s;21;i;ender portal;n;&6Magma Cube;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.bat.%player%} is true:
				if {effects.disguises.bat.%player%} is 0:
					set {_temp.d13.%player%} to "s;23;i;bat spawn egg;n;&6Bat;l;&7Currently &aEnabled;c;sudo %player% disguiseset bat"
				if {effects.disguises.bat.%player%} is 1:
					set {_temp.d13.%player%} to "s;23;i;bat spawn egg;n;&6Bat;l;&7Currently &cDisabled;c;sudo %player% disguiseset bat"
			if {db_effectshop.disguises.bat.%player%} is false:
				set {_temp.d13.%player%} to "s;23;i;ender portal;n;&6Bat;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.witch.%player%} is true:
				if {effects.disguises.witch.%player%} is 0:
					set {_temp.d14.%player%} to "s;25;i;witch spawn egg;n;&6Witch;l;&7Currently &aEnabled;c;sudo %player% disguiseset witch"
				if {effects.disguises.witch.%player%} is 1:
					set {_temp.d14.%player%} to "s;25;i;witch spawn egg;n;&6Witch;l;&7Currently &cDisabled;c;sudo %player% disguiseset witch"
			if {db_effectshop.disguises.witch.%player%} is false:
				set {_temp.d14.%player%} to "s;25;i;ender portal;n;&6Witch;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.pig.%player%} is true:
				if {effects.disguises.pig.%player%} is 0:
					set {_temp.d15.%player%} to "s;27;i;pig spawn egg;n;&6Pig;l;&7Currently &aEnabled;c;sudo %player% disguiseset pig"
				if {effects.disguises.pig.%player%} is 1:
					set {_temp.d15.%player%} to "s;27;i;pig spawn egg;n;&6Pig;l;&7Currently &cDisabled;c;sudo %player% disguiseset pig"
			if {db_effectshop.disguises.pig.%player%} is false:
				set {_temp.d15.%player%} to "s;27;i;ender portal;n;&6Pig;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.sheep.%player%} is true:
				if {effects.disguises.sheep.%player%} is 0:
					set {_temp.d16.%player%} to "s;28;i;sheep spawn egg;n;&6Sheep;l;&7Currently &aEnabled;c;sudo %player% disguiseset sheep"
				if {effects.disguises.sheep.%player%} is 1:
					set {_temp.d16.%player%} to "s;28;i;sheep spawn egg;n;&6Sheep;l;&7Currently &cDisabled;c;sudo %player% disguiseset sheep"
			if {db_effectshop.disguises.sheep.%player%} is false:
				set {_temp.d16.%player%} to "s;28;i;ender portal;n;&6Sheep;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.cow.%player%} is true:
				if {effects.disguises.cow.%player%} is 0:
					set {_temp.d17.%player%} to "s;30;i;cow spawn egg;n;&6Cow;l;&7Currently &aEnabled;c;sudo %player% disguiseset cow"
				if {effects.disguises.cow.%player%} is 1:
					set {_temp.d17.%player%} to "s;30;i;cow spawn egg;n;&6Cow;l;&7Currently &cDisabled;c;sudo %player% disguiseset cow"
			if {db_effectshop.disguises.cow.%player%} is false:
				set {_temp.d17.%player%} to "s;30;i;ender portal;n;&6Cow;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.chicken.%player%} is true:
				if {effects.disguises.chicken.%player%} is 0:
					set {_temp.d18.%player%} to "s;32;i;chicken spawn egg;n;&6Chicken;l;&7Currently &aEnabled;c;sudo %player% disguiseset chicken"
				if {effects.disguises.chicken.%player%} is 1:
					set {_temp.d18.%player%} to "s;32;i;chicken spawn egg;n;&6Chicken;l;&7Currently &cDisabled;c;sudo %player% disguiseset chicken"
			if {db_effectshop.disguises.chicken.%player%} is false:
				set {_temp.d18.%player%} to "s;32;i;ender portal;n;&6Chicken;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.squid.%player%} is true:
				if {effects.disguises.squid.%player%} is 0:
					set {_temp.d19.%player%} to "s;34;i;squid spawn egg;n;&6Squid;l;&7Currently &aEnabled;c;sudo %player% disguiseset squid"
				if {effects.disguises.squid.%player%} is 1:
					set {_temp.d19.%player%} to "s;34;i;squid spawn egg;n;&6Squid;l;&7Currently &cDisabled;c;sudo %player% disguiseset squid"
			if {db_effectshop.disguises.squid.%player%} is false:
				set {_temp.d19.%player%} to "s;34;i;ender portal;n;&6Squid;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.wolf.%player%} is true:
				if {effects.disguises.wolf.%player%} is 0:
					set {_temp.d20.%player%} to "s;36;i;wolf spawn egg;n;&6Wolf;l;&7Currently &aEnabled;c;sudo %player% disguiseset wolf"
				if {effects.disguises.wolf.%player%} is 1:
					set {_temp.d20.%player%} to "s;36;i;wolf spawn egg;n;&6Wolf;l;&7Currently &cDisabled;c;sudo %player% disguiseset wolf"
			if {db_effectshop.disguises.wolf.%player%} is false:
				set {_temp.d20.%player%} to "s;36;i;ender portal;n;&6Wolf;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.mooshroom.%player%} is true:
				if {effects.disguises.mooshroom.%player%} is 0:
					set {_temp.d21.%player%} to "s;37;i;mooshroom spawn egg;n;&6Mooshroom;l;&7Currently &aEnabled;c;sudo %player% disguiseset mooshroom"
				if {effects.disguises.mooshroom.%player%} is 1:
					set {_temp.d21.%player%} to "s;37;i;mooshroom spawn egg;n;&6Mooshroom;l;&7Currently &cDisabled;c;sudo %player% disguiseset mooshroom"
			if {db_effectshop.disguises.mooshroom.%player%} is false:
				set {_temp.d21.%player%} to "s;37;i;ender portal;n;&6Mooshroom;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.ocelot.%player%} is true:
				if {effects.disguises.ocelot.%player%} is 0:
					set {_temp.d22.%player%} to "s;39;i;ocelot spawn egg;n;&6Ocelot;l;&7Currently &aEnabled;c;sudo %player% disguiseset ocelot"
				if {effects.disguises.ocelot.%player%} is 1:
					set {_temp.d22.%player%} to "s;39;i;ocelot spawn egg;n;&6Ocelot;l;&7Currently &cDisabled;c;sudo %player% disguiseset ocelot"
			if {db_effectshop.disguises.ocelot.%player%} is false:
				set {_temp.d22.%player%} to "s;39;i;ender portal;n;&6Ocelot;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.horse.%player%} is true:
				if {effects.disguises.horse.%player%} is 0:
					set {_temp.d23.%player%} to "s;41;i;horse spawn egg;n;&6Horse;l;&7Currently &aEnabled;c;sudo %player% disguiseset horse"
				if {effects.disguises.horse.%player%} is 1:
					set {_temp.d23.%player%} to "s;41;i;horse spawn egg;n;&6Horse;l;&7Currently &cDisabled;c;sudo %player% disguiseset horse"
			if {db_effectshop.disguises.horse.%player%} is false:
				set {_temp.d23.%player%} to "s;41;i;ender portal;n;&6Horse;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			if {db_effectshop.disguises.villager.%player%} is true:
				if {effects.disguises.villager.%player%} is 0:
					set {_temp.d24.%player%} to "s;43;i;villager spawn egg;n;&6Villager;l;&7Currently &aEnabled;c;sudo %player% disguiseset villager"
				if {effects.disguises.villager.%player%} is 1:
					set {_temp.d24.%player%} to "s;43;i;villager spawn egg;n;&6Villager;l;&7Currently &cDisabled;c;sudo %player% disguiseset villager"
			if {db_effectshop.disguises.villager.%player%} is false:
				set {_temp.d24.%player%} to "s;43;i;ender portal;n;&6Villager;l;&3Not Unlocked|| ||&eType &f/effect shop &eor||&ebuy on &fOBAM Shop &eto unlock.;c;sudo %player% effect disguise"
			show "%{_temp.d1.%player%}%;%{_temp.d2.%player%}%;%{_temp.d3.%player%}%;%{_temp.d4.%player%}%;%{_temp.d5.%player%}%;%{_temp.d6.%player%}%;%{_temp.d7.%player%}%;%{_temp.d8.%player%}%;%{_temp.d9.%player%}%;%{_temp.d10.%player%}%;%{_temp.d11.%player%}%;%{_temp.d12.%player%}%;%{_temp.d13.%player%}%;%{_temp.d14.%player%}%;%{_temp.d15.%player%}%;%{_temp.d16.%player%}%;%{_temp.d17.%player%}%;%{_temp.d18.%player%}%;%{_temp.d19.%player%}%;%{_temp.d20.%player%}%;%{_temp.d21.%player%}%;%{_temp.d22.%player%}%;%{_temp.d23.%player%}%;%{_temp.d24.%player%}%;{@dDspecial};{@dStop}" with 6 rows named "&3Disguise &2Closet" to player
			stop
		if argument is "creeper":
			if {db_effectshop.disguises.creeper.%player%} is true:
				if {effects.disguises.creeper.%player%} is 1:
					send "&fYou are already disguised as a creeper." to player
					stop
				if {effects.disguises.creeper.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.creeper.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "creeper"
					make console execute command "/disguiseplayer %player% creeper"
					send "&eYou are now disguised as a creeper." to player
					stop
			if {db_effectshop.disguises.creeper.%player%} is false:
				send "&fYou need to unlock the creeper to disguise as it." to player
		if argument is "skeleton":
			if {db_effectshop.disguises.skeleton.%player%} is true:
				if {effects.disguises.skeleton.%player%} is 1:
					send "&fYou are already disguised as a skeleton." to player
					stop
				if {effects.disguises.skeleton.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.skeleton.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "skeleton"
					make console execute command "/disguiseplayer %player% skeleton"
					send "&eYou are now disguised as a skeleton." to player
					stop
			if {db_effectshop.disguises.skeleton.%player%} is false:
				send "&fYou need to unlock the skeleton to disguise as it." to player
		if argument is "spider":
			if {db_effectshop.disguises.spider.%player%} is true:
				if {effects.disguises.spider.%player%} is 1:
					send "&fYou are already disguised as a spider." to player
					stop
				if {effects.disguises.spider.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.spider.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "spider"
					make console execute command "/disguiseplayer %player% spider"
					send "&eYou are now disguised as a spider." to player
					stop
			if {db_effectshop.disguises.spider.%player%} is false:
				send "&fYou need to unlock the spider to disguise as it." to player
		if argument is "zombie":
			if {db_effectshop.disguises.zombie.%player%} is true:
				if {effects.disguises.zombie.%player%} is 1:
					send "&fYou are already disguised as a zombie." to player
					stop
				if {effects.disguises.zombie.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.zombie.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "zombie"
					make console execute command "/disguiseplayer %player% zombie"
					send "&eYou are now disguised as a zombie." to player
					stop
			if {db_effectshop.disguises.zombie.%player%} is false:
				send "&fYou need to unlock the zombie to disguise as it." to player
		if argument is "slime":
			if {db_effectshop.disguises.slime.%player%} is true:
				if {effects.disguises.slime.%player%} is 1:
					send "&fYou are already disguised as a slime." to player
					stop
				if {effects.disguises.slime.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.slime.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "slime"
					make console execute command "/disguiseplayer %player% slime"
					send "&eYou are now disguised as a slime." to player
					stop
			if {db_effectshop.disguises.slime.%player%} is false:
				send "&fYou need to unlock the slime to disguise as it." to player
		if argument is "ghast":
			if {db_effectshop.disguises.ghast.%player%} is true:
				if {effects.disguises.ghast.%player%} is 1:
					send "&fYou are already disguised as a ghast." to player
					stop
				if {effects.disguises.ghast.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.ghast.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "ghast"
					make console execute command "/disguiseplayer %player% ghast"
					send "&eYou are now disguised as a ghast." to player
					stop
			if {db_effectshop.disguises.ghast.%player%} is false:
				send "&fYou need to unlock the ghast to disguise as it." to player
		if argument is "zombiepigman":
			if {db_effectshop.disguises.zombiepigman.%player%} is true:
				if {effects.disguises.zombiepigman.%player%} is 1:
					send "&fYou are already disguised as a zombie pigman." to player
					stop
				if {effects.disguises.zombiepigman.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.zombiepigman.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "zombiepigman"
					make console execute command "/disguiseplayer %player% pig_zombie"
					send "&eYou are now disguised as a zombie pigman." to player
					stop
			if {db_effectshop.disguises.zombiepigman.%player%} is false:
				send "&fYou need to unlock the zombie pigman to disguise as it." to player
		if argument is "enderman":
			if {db_effectshop.disguises.enderman.%player%} is true:
				if {effects.disguises.enderman.%player%} is 1:
					send "&fYou are already disguised as a enderman." to player
					stop
				if {effects.disguises.enderman.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.enderman.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "enderman"
					make console execute command "/disguiseplayer %player% enderman"
					send "&eYou are now disguised as a enderman." to player
					stop
			if {db_effectshop.disguises.enderman.%player%} is false:
				send "&fYou need to unlock the enderman to disguise as it." to player
		if argument is "cavespider":
			if {db_effectshop.disguises.cavespider.%player%} is true:
				if {effects.disguises.cavespider.%player%} is 1:
					send "&fYou are already disguised as a cave spider." to player
					stop
				if {effects.disguises.cavespider.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.cavespider.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "cavespider"
					make console execute command "/disguiseplayer %player% cave_spider"
					send "&eYou are now disguised as a cave spider." to player
					stop
			if {db_effectshop.disguises.cavespider.%player%} is false:
				send "&fYou need to unlock the cave spider to disguise as it." to player
		if argument is "silverfish":
			if {db_effectshop.disguises.silverfish.%player%} is true:
				if {effects.disguises.silverfish.%player%} is 1:
					send "&fYou are already disguised as a silverfish." to player
					stop
				if {effects.disguises.silverfish.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.silverfish.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "silverfish"
					make console execute command "/disguiseplayer %player% silverfish"
					send "&eYou are now disguised as a silverfish." to player
					stop
			if {db_effectshop.disguises.silverfish.%player%} is false:
				send "&fYou need to unlock the silverfish to disguise as it." to player
		if argument is "blaze":
			if {db_effectshop.disguises.blaze.%player%} is true:
				if {effects.disguises.blaze.%player%} is 1:
					send "&fYou are already disguised as a blaze." to player
					stop
				if {effects.disguises.blaze.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.blaze.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "blaze"
					make console execute command "/disguiseplayer %player% blaze"
					send "&eYou are now disguised as a blaze." to player
					stop
			if {db_effectshop.disguises.blaze.%player%} is false:
				send "&fYou need to unlock the blaze to disguise as it." to player
		if argument is "magmacube":
			if {db_effectshop.disguises.magmacube.%player%} is true:
				if {effects.disguises.magmacube.%player%} is 1:
					send "&fYou are already disguised as a magma cube." to player
					stop
				if {effects.disguises.magmacube.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.magmacube.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "magmacube"
					make console execute command "/disguiseplayer %player% magma_cube"
					send "&eYou are now disguised as a magma cube." to player
					stop
			if {db_effectshop.disguises.magmacube.%player%} is false:
				send "&fYou need to unlock the magma cube to disguise as it." to player
		if argument is "bat":
			if {db_effectshop.disguises.bat.%player%} is true:
				if {effects.disguises.bat.%player%} is 1:
					send "&fYou are already disguised as a bat." to player
					stop
				if {effects.disguises.bat.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.bat.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "bat"
					make console execute command "/disguiseplayer %player% bat"
					send "&eYou are now disguised as a bat." to player
					stop
			if {db_effectshop.disguises.bat.%player%} is false:
				send "&fYou need to unlock the bat to disguise as it." to player
		if argument is "witch":
			if {db_effectshop.disguises.witch.%player%} is true:
				if {effects.disguises.witch.%player%} is 1:
					send "&fYou are already disguised as a witch." to player
					stop
				if {effects.disguises.witch.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.witch.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "witch"
					make console execute command "/disguiseplayer %player% witch"
					send "&eYou are now disguised as a witch." to player
					stop
			if {db_effectshop.disguises.witch.%player%} is false:
				send "&fYou need to unlock the witch to disguise as it." to player
		if argument is "pig":
			if {db_effectshop.disguises.pig.%player%} is true:
				if {effects.disguises.pig.%player%} is 1:
					send "&fYou are already disguised as a pig." to player
					stop
				if {effects.disguises.pig.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.pig.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "pig"
					make console execute command "/disguiseplayer %player% pig"
					send "&eYou are now disguised as a pig." to player
					stop
			if {db_effectshop.disguises.pig.%player%} is false:
				send "&fYou need to unlock the pig to disguise as it." to player
		if argument is "sheep":
			if {db_effectshop.disguises.sheep.%player%} is true:
				if {effects.disguises.sheep.%player%} is 1:
					send "&fYou are already disguised as a sheep." to player
					stop
				if {effects.disguises.sheep.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.sheep.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "sheep"
					make console execute command "/disguiseplayer %player% sheep"
					send "&eYou are now disguised as a sheep." to player
					stop
			if {db_effectshop.disguises.sheep.%player%} is false:
				send "&fYou need to unlock the sheep to disguise as it." to player
		if argument is "cow":
			if {db_effectshop.disguises.cow.%player%} is true:
				if {effects.disguises.cow.%player%} is 1:
					send "&fYou are already disguised as a cow." to player
					stop
				if {effects.disguises.cow.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.cow.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "cow"
					make console execute command "/disguiseplayer %player% cow"
					send "&eYou are now disguised as a cow." to player
					stop
			if {db_effectshop.disguises.cow.%player%} is false:
				send "&fYou need to unlock the cow to disguise as it." to player
		if argument is "chicken":
			if {db_effectshop.disguises.chicken.%player%} is true:
				if {effects.disguises.chicken.%player%} is 1:
					send "&fYou are already disguised as a chicken." to player
					stop
				if {effects.disguises.chicken.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.chicken.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "chicken"
					make console execute command "/disguiseplayer %player% chicken"
					send "&eYou are now disguised as a chicken." to player
					stop
			if {db_effectshop.disguises.chicken.%player%} is false:
				send "&fYou need to unlock the chicken to disguise as it." to player
		if argument is "squid":
			if {db_effectshop.disguises.squid.%player%} is true:
				if {effects.disguises.squid.%player%} is 1:
					send "&fYou are already disguised as a squid." to player
					stop
				if {effects.disguises.squid.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.squid.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "squid"
					make console execute command "/disguiseplayer %player% squid"
					send "&eYou are now disguised as a squid." to player
					stop
			if {db_effectshop.disguises.squid.%player%} is false:
				send "&fYou need to unlock the squid to disguise as it." to player
		if argument is "wolf":
			if {db_effectshop.disguises.wolf.%player%} is true:
				if {effects.disguises.wolf.%player%} is 1:
					send "&fYou are already disguised as a wolf." to player
					stop
				if {effects.disguises.wolf.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.wolf.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "wolf"
					make console execute command "/disguiseplayer %player% wolf"
					send "&eYou are now disguised as a wolf." to player
					stop
			if {db_effectshop.disguises.wolf.%player%} is false:
				send "&fYou need to unlock the wolf to disguise as it." to player
		if argument is "mooshroom":
			if {db_effectshop.disguises.mooshroom.%player%} is true:
				if {effects.disguises.mooshroom.%player%} is 1:
					send "&fYou are already disguised as a mooshroom." to player
					stop
				if {effects.disguises.mooshroom.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.mooshroom.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "mooshroom"
					make console execute command "/disguiseplayer %player% mushroom_cow"
					send "&eYou are now disguised as a mooshroom." to player
					stop
			if {db_effectshop.disguises.mooshroom.%player%} is false:
				send "&fYou need to unlock the mooshroom to disguise as it." to player
		if argument is "ocelot":
			if {db_effectshop.disguises.ocelot.%player%} is true:
				if {effects.disguises.ocelot.%player%} is 1:
					send "&fYou are already disguised as a ocelot." to player
					stop
				if {effects.disguises.ocelot.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.ocelot.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "ocelot"
					make console execute command "/disguiseplayer %player% ocelot"
					send "&eYou are now disguised as a ocelot." to player
					stop
			if {db_effectshop.disguises.ocelot.%player%} is false:
				send "&fYou need to unlock the ocelot to disguise as it." to player
		if argument is "horse":
			if {db_effectshop.disguises.horse.%player%} is true:
				if {effects.disguises.horse.%player%} is 1:
					send "&fYou are already disguised as a horse." to player
					stop
				if {effects.disguises.horse.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.horse.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "horse"
					make console execute command "/disguiseplayer %player% horse"
					send "&eYou are now disguised as a horse." to player
					stop
			if {db_effectshop.disguises.horse.%player%} is false:
				send "&fYou need to unlock the horse to disguise as it." to player
		if argument is "villager":
			if {db_effectshop.disguises.villager.%player%} is true:
				if {effects.disguises.villager.%player%} is 1:
					send "&fYou are already disguised as a villager." to player
					stop
				if {effects.disguises.villager.%player%} is 0:
					set {effects.disguises.%{disguise.type.%player%}%.%player%} to 0
					set {effects.disguises.villager.%player%} to 1
					set {disguise.set.%player%} to true
					set {disguise.type.%player%} to "villager"
					make console execute command "/disguiseplayer %player% villager"
					send "&eYou are now disguised as a villager." to player
					stop
			if {db_effectshop.disguises.villager.%player%} is false:
				send "&fYou need to unlock the villager to disguise as it." to player
		if argument is "special":
			send "test" to player
			stop
		if argument is "remove":
			if {disguise.set.%player%} is false:
				send "&cYou are currently not disguised." to player
				stop
			if {disguise.set.%player%} is true:
				make console execute command "/undisguiseplayer %player%"
				set {disguise.set.%player%} to false
				send "&eYou are now undisguised." to player
				stop
